google:
  username: 2020010001574@gndu.ac.in
  password: $outhAsia1997

meet:
  minimum_participants_before_exiting_meet: 3
  link_to_search_for_in_whatsapp: meet.google.com

whatsapp:
  groups_to_search_in:        
        - Automation

obs:
  record_meetings: 1
  location_to_obs_shortcut: C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\OBS Studio\\OBS Studio (64bit).lnk

time:
  time_in_minutes_to_search_for_messages_in_whatsapp: 15
  time_in_seconds_to_wait_before_logout_checker_starts: 10
